function draw_one_raster_timeframe_for_one_region( ...
    ax, spike_data, params, current_time, region)

relevant_axis           = ax.(region);

[raster_mat, z_scored_spiking_mat, raster_celltype_labels] = ...
    sg_disp.plotting.extract_raster_data_for_one_timeframe(...
    spike_data, params, current_time, region);

if isempty( raster_mat )
    text( relevant_axis, 0.5, 0.5, ...
            sprintf('No units in %s for this session', region), ...
            'Color', 'red', ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 12);
    title( relevant_axis, 'No units in region' );
else
    imagesc( relevant_axis, z_scored_spiking_mat );
end

end