function [fig, session_menu, run_menu, all_sessions, runs_in_session] = make_dropdown_menus(fig,...
        params, callback_function)

menu_pos_wrt_fig = params.menu_pos_wrt_fig; % x and y relative to figure (0 to 1)
menu_width = params.menu_width;
menu_height = params.menu_height;
menu_x_offset = params.menu_x_offset;
run_menu_y_offset = params.run_menu_y_offset;
menu_font_size = params.menu_font_size;

session_per_file = params.session_per_file;
current_session = params.current_session;
run_number_per_file = params.run_number_per_file;

all_sessions = unique(session_per_file);

% Set figure units to pixels
set(fig, 'Units', 'pixels');
% Get figure position in pixels
fig_position_px = get(fig, 'Position');

session_text_x = fig_position_px(3) * menu_pos_wrt_fig(1);
session_text_y = fig_position_px(4) * menu_pos_wrt_fig(2);
session_menu_x = fig_position_px(3) * (menu_pos_wrt_fig(1) + menu_x_offset);
session_menu_y = session_text_y;

% Create dropdown menu for session
session_text = uicontrol('Parent', fig, ...
    'Style', 'text', ...
    'FontSize', menu_font_size, ...
    'Position', [session_text_x, session_text_y, menu_width, menu_height], ...
    'String', 'Session: ', ...
    'HorizontalAlignment', 'right');
session_menu = uicontrol('Parent', fig, ...
    'Style', 'popupmenu', ...
    'FontSize', menu_font_size, ...
    'Position', [session_menu_x, session_menu_y, menu_width, menu_height], ...
    'String', all_sessions, ...
    'Callback', callback_function);  % Set callback function handle

sessionIdx = get(session_menu, 'Value');
if isempty(current_session)
    current_session = all_sessions{sessionIdx};
end
runs_in_session = run_number_per_file( strcmp(session_per_file, current_session) );

run_text_x = fig_position_px(3) * menu_pos_wrt_fig(1);
run_text_y = fig_position_px(4) * (menu_pos_wrt_fig(2) - run_menu_y_offset);
run_menu_x = fig_position_px(3) * (menu_pos_wrt_fig(1) + menu_x_offset);
run_menu_y = run_text_y;

run_text = uicontrol('Parent', fig, ...
    'Style', 'text', ...
    'FontSize', menu_font_size, ...
    'Position', [run_text_x, run_text_y , menu_width, menu_height], ...
    'String', 'Run Number:', ...
    'HorizontalAlignment', 'right');
run_menu = uicontrol('Parent', fig, ...
    'Style', 'popupmenu', ...
    'FontSize', menu_font_size, ...
    'Position', [run_menu_x, run_menu_y, menu_width, menu_height], ...
    'String', runs_in_session, ...
    'Callback', callback_function);  % Set callback function handle

end
